# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login_and_registration', '0001_initial'),
        ('app_the_wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='liked_comments', to='app_login_and_registration.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='liked_messages', to='app_login_and_registration.User'),
        ),
    ]
