# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_the_wall', '0002_auto_20190221_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='null author', max_length=45),
            preserve_default=False,
        ),
    ]
