# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_the_wall', '0003_message_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='message',
            new_name='quote',
        ),
    ]
